# Generated by Django 5.2.7 on 2025-11-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="ml",
            field=models.CharField(default="0", max_length=5),
        ),
    ]
