# Generated by Django 5.1.5 on 2025-11-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_produto_ml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
    ]
