# Generated by Django 5.1.5 on 2025-11-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_remove_produto_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(),
        ),
    ]
