# Generated by Django 5.1.5 on 2025-11-13 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_categoria_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=128)),
                ('CPF', models.CharField(max_length=15)),
                ('data_nascimento', models.DateTimeField(null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('genero', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_principal',
            field=models.ImageField(upload_to='./produtos/'),
        ),
        migrations.CreateModel(
            name='enderecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.usuario')),
            ],
        ),
    ]
