# Generated by Django 5.1.5 on 2025-11-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_itempedido_pedido_itempedido_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_usuario',
            field=models.CharField(default='Comum', max_length=200),
        ),
    ]
