# Generated by Django 5.1.5 on 2025-11-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_produto_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(default='Comum', max_length=200),
        ),
    ]
