# Generated by Django 5.1.5 on 2025-11-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_remove_produto_tipo_usuario_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
