# Generated by Django 5.2.7 on 2025-10-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("marca", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "preco_promocional",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("estoque", models.PositiveIntegerField(default=0)),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("imagem_principal", models.ImageField(upload_to="produtos/")),
                ("tamanho", models.CharField(blank=True, max_length=50, null=True)),
                ("cor", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "avaliacao_media",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("quantidade_avaliacoes", models.PositiveIntegerField(default=0)),
                ("ativo", models.BooleanField(default=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="loja.categoria",
                    ),
                ),
            ],
        ),
    ]
